# Load packages and initialize

In [3]:
import os
import pickle
import DatastreamDSWS as DSWS
import pandas as pd
import numpy as np
from collections import OrderedDict
from decimal import Decimal
TWOPLACES = Decimal('0.01')
from pypf.chart import PFChart
with open('instrument_object.pkl', 'rb') as input:
    i = pickle.load(input)
ds = DSWS.Datastream(username='ZMLY052', password='TORCH478')

# Save an empty YahooSecurity object in pickle format (One-time use only)

In [4]:
def pnf_signal(df, plot_chart=False, min_period=100):
    df.index = pd.to_datetime(df.index).strftime('%Y-%m-%d')
    df = df.dropna()
    if df.shape[0] > min_period:
        i._symbol = df.name
        dat = OrderedDict()
        for index, value in df.items():
            d = OrderedDict()
            d['Date'] = index
            d['Open'] = Decimal(value)
            d['High'] = Decimal(value)
            d['Low'] = Decimal(value)
            d['Close'] = Decimal(value)
            d['Volume'] = 0
            dat[index] = d
        c = PFChart(i,
                    box_size=0.0325,
                    duration=duration,
                    reversal=3,
                    method='c',
                    style=True,
                    trend_lines=True)
        c.security.historical_data = dat
        c.create_chart()
        if c.current_signal == 'buy' and c.current_status == 'bull confirmed':
            signal = 2
        elif c.current_signal == 'buy' and c.current_status == 'bull correction':
            signal = 1
        elif c.current_signal == 'sell' and c.current_status == 'bear correction':
            signal = -1
        elif c.current_signal == 'sell' and c.current_status == 'bear confirmed':
            signal = -2
        else:
            signal = 0
        if plot_chart:
            print(c.chart)
    else:
        signal = np.nan
    return (signal)

In [24]:
symbols = [
    'U:VT', 'U:VTI', '@VXUS',
    'U:EFA', 'U:EWJ', 'U:EWU', 'U:EZU', 'U:EWL', 'U:EWD', 'U:NORW', 'U:EWA', 'U:EWH', 'U:EPP',
    'U:EEM', '@MCHI', 'U:EWT', 'U:EWY', 'U:INDA', 'U:EWZ',
    'U:IWM', 'U:VTV', 'U:VUG',
    'U:XLC', 'U:XLY', 'U:XLP', 'U:XLE', 'U:XLF', 'U:XLV', 'U:XLI', 'U:XLB',
    'U:XLRE', 'U:XLK', 'U:XLU', 'U:AGG', '@BNDX', '@TLT', 'U:LQD', 'U:HYG',
    'U:MUB', 'U:HYD', 'U:BIL', '@QQQ', 'U:DIA'
]
df = ds.get_data(tickers=",".join(symbols), fields=['RI'], start='2017-01-01')
# df = pd.read_pickle("data.pickle")

Instrument,U:VT,U:VTI,@VXUS,U:EFA,U:EWJ,U:EWU,U:EZU,U:EWL,U:EWD,U:NORW,...,U:AGG,@BNDX,@TLT,U:LQD,U:HYG,U:MUB,U:HYD,U:BIL,@QQQ,U:DIA
Field,RI,RI,RI,RI,RI,RI,RI,RI,RI,RI,...,RI,RI,RI,RI,RI,RI,RI,RI,RI,RI
Currency,U$,U$,U$,U$,U$,U$,U$,U$,U$,U$,...,U$,U$,U$,U$,U$,U$,U$,U$,U$,U$
Dates,,,,,,,,,,,,,,,,,,,,,
2016-12-30,147.67,268.69,111.26,201.75,99.48,263.37,135.06,348.87,461.83,155.62,...,166.99,114.54,251.65,220.55,166.73,142.22,175.91,105.89,256.62,377.72
2017-01-02,147.67,268.69,111.26,201.75,99.48,263.37,135.06,348.87,461.83,155.62,...,166.99,114.54,251.65,220.55,166.73,142.22,175.91,105.89,256.62,377.72
2017-01-03,148.88,270.74,112.06,203.01,100.30,264.40,135.37,350.17,465.04,156.36,...,167.16,114.14,252.72,220.74,167.42,142.09,175.61,105.94,258.92,379.46
2017-01-04,150.24,272.81,113.30,205.31,102.31,266.97,136.23,353.61,467.61,157.75,...,167.21,114.20,253.70,221.50,168.33,142.38,175.91,105.94,260.33,380.86
2017-01-05,150.72,272.28,114.15,207.06,102.90,268.77,137.37,357.87,469.22,159.39,...,167.90,114.12,257.67,222.68,168.08,142.66,176.44,105.92,261.80,380.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-22,267.13,564.19,163.85,304.93,140.65,356.40,209.14,624.48,694.38,231.26,...,176.31,119.67,248.85,246.80,197.27,161.77,197.81,112.90,832.07,741.82
2023-06-23,264.20,559.54,161.30,300.19,137.18,352.98,205.98,623.93,687.36,223.71,...,176.83,120.28,251.33,247.49,196.93,162.24,198.15,112.93,823.82,737.06
2023-06-26,264.03,557.59,161.71,300.57,137.18,353.09,206.45,622.70,691.37,226.66,...,177.05,120.60,251.60,247.77,197.03,162.26,198.15,112.95,812.77,737.01
2023-06-27,266.74,564.38,163.09,303.19,137.70,355.07,209.61,628.17,697.99,225.62,...,176.71,120.45,250.94,247.49,197.70,162.24,197.89,112.99,826.75,741.58
2023-06-28,266.88,564.85,162.91,303.41,139.23,352.76,210.03,624.48,697.19,226.64,...,177.23,120.73,252.01,248.57,198.84,162.48,198.12,113.02,828.36,740.27

In [20]:
fields = ['PO', 'PH', 'PL', 'RI']
duration = 20
end = pd.to_datetime('today') - pd.DateOffset(days=1)
start = end - pd.DateOffset(years=duration)
dat = {'open': None, 'high': None, 'low': None, 'close': None}
for f in fields:
    if f == 'PO':
        dat['open'] = df
    elif f == 'PH':
        dat['high'] = df
    elif f == 'PL':
        dat['low'] = df
    elif f == 'RI':
        dat['close'] = df
dat

{'open': Instrument    U:VT   U:VTI   @VXUS   U:EFA   U:EWJ   U:EWU   U:EZU   U:EWL  \
 Field           RI      RI      RI      RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$      U$      U$      U$
 Dates
 2016-12-30  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-02  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-03  148.88  270.74  112.06  203.01  100.30  264.40  135.37  350.17
 2017-01-04  150.24  272.81  113.30  205.31  102.31  266.97  136.23  353.61
 2017-01-05  150.72  272.28  114.15  207.06  102.90  268.77  137.37  357.87
 ...            ...     ...     ...     ...     ...     ...     ...     ...
 2023-06-15  271.51  570.75  167.40  311.15  143.48  363.57  212.77  635.69
 2023-06-16  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-19  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-20  268.07  565.80  164.58  306.37  140.15  359.04  210.40  624.75
 2023-06-21  267.24  562.69  164.73  306.83  141.82  358.49  210.10  623.66

 Instrument   U:EWD  U:NORW  ...   U:AGG   @BNDX    @TLT   U:LQD   U:HYG  \
 Field           RI      RI  ...      RI      RI      RI      RI      RI
 Currency        U$      U$  ...      U$      U$      U$      U$      U$
 Dates                       ...
 2016-12-30  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-02  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-03  465.04  156.36  ...  167.16  114.14  252.72  220.74  167.42
 2017-01-04  467.61  157.75  ...  167.21  114.20  253.70  221.50  168.33
 2017-01-05  469.22  159.39  ...  167.90  114.12  257.67  222.68  168.08
 ...            ...     ...  ...     ...     ...     ...     ...     ...
 2023-06-15  726.47  239.91  ...  177.17  119.69  250.53  247.91  199.39
 2023-06-16  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-19  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-20  701.00  233.93  ...  176.94  120.11  251.28  248.37  198.36
 2023-06-21  702.20  233.97  ...  177.23  120.13  251.89  248.09  197.86

 Instrument   U:MUB   U:HYD   U:BIL    @QQQ   U:DIA
 Field           RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$
 Dates
 2016-12-30  142.22  175.91  105.89  256.62  377.72
 2017-01-02  142.22  175.91  105.89  256.62  377.72
 2017-01-03  142.09  175.61  105.94  258.92  379.46
 2017-01-04  142.38  175.91  105.94  260.33  380.86
 2017-01-05  142.66  176.44  105.92  261.80  380.09
 ...            ...     ...     ...     ...     ...
 2023-06-15  162.03  197.58  112.75  840.21  751.99
 2023-06-16  161.92  197.62  112.77  834.92  749.72
 2023-06-19  161.92  197.62  112.79  834.92  749.72
 2023-06-20  162.12  197.58  112.83  833.72  744.27
 2023-06-21  162.27  198.04  112.84  822.36  742.02

 [1689 rows x 43 columns],
 'high': Instrument    U:VT   U:VTI   @VXUS   U:EFA   U:EWJ   U:EWU   U:EZU   U:EWL  \
 Field           RI      RI      RI      RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$      U$      U$      U$
 Dates
 2016-12-30  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-02  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-03  148.88  270.74  112.06  203.01  100.30  264.40  135.37  350.17
 2017-01-04  150.24  272.81  113.30  205.31  102.31  266.97  136.23  353.61
 2017-01-05  150.72  272.28  114.15  207.06  102.90  268.77  137.37  357.87
 ...            ...     ...     ...     ...     ...     ...     ...     ...
 2023-06-15  271.51  570.75  167.40  311.15  143.48  363.57  212.77  635.69
 2023-06-16  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-19  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-20  268.07  565.80  164.58  306.37  140.15  359.04  210.40  624.75
 2023-06-21  267.24  562.69  164.73  306.83  141.82  358.49  210.10  623.66

 Instrument   U:EWD  U:NORW  ...   U:AGG   @BNDX    @TLT   U:LQD   U:HYG  \
 Field           RI      RI  ...      RI      RI      RI      RI      RI
 Currency        U$      U$  ...      U$      U$      U$      U$      U$
 Dates                       ...
 2016-12-30  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-02  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-03  465.04  156.36  ...  167.16  114.14  252.72  220.74  167.42
 2017-01-04  467.61  157.75  ...  167.21  114.20  253.70  221.50  168.33
 2017-01-05  469.22  159.39  ...  167.90  114.12  257.67  222.68  168.08
 ...            ...     ...  ...     ...     ...     ...     ...     ...
 2023-06-15  726.47  239.91  ...  177.17  119.69  250.53  247.91  199.39
 2023-06-16  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-19  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-20  701.00  233.93  ...  176.94  120.11  251.28  248.37  198.36
 2023-06-21  702.20  233.97  ...  177.23  120.13  251.89  248.09  197.86

 Instrument   U:MUB   U:HYD   U:BIL    @QQQ   U:DIA
 Field           RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$
 Dates
 2016-12-30  142.22  175.91  105.89  256.62  377.72
 2017-01-02  142.22  175.91  105.89  256.62  377.72
 2017-01-03  142.09  175.61  105.94  258.92  379.46
 2017-01-04  142.38  175.91  105.94  260.33  380.86
 2017-01-05  142.66  176.44  105.92  261.80  380.09
 ...            ...     ...     ...     ...     ...
 2023-06-15  162.03  197.58  112.75  840.21  751.99
 2023-06-16  161.92  197.62  112.77  834.92  749.72
 2023-06-19  161.92  197.62  112.79  834.92  749.72
 2023-06-20  162.12  197.58  112.83  833.72  744.27
 2023-06-21  162.27  198.04  112.84  822.36  742.02

 [1689 rows x 43 columns],
 'low': Instrument    U:VT   U:VTI   @VXUS   U:EFA   U:EWJ   U:EWU   U:EZU   U:EWL  \
 Field           RI      RI      RI      RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$      U$      U$      U$
 Dates
 2016-12-30  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-02  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-03  148.88  270.74  112.06  203.01  100.30  264.40  135.37  350.17
 2017-01-04  150.24  272.81  113.30  205.31  102.31  266.97  136.23  353.61
 2017-01-05  150.72  272.28  114.15  207.06  102.90  268.77  137.37  357.87
 ...            ...     ...     ...     ...     ...     ...     ...     ...
 2023-06-15  271.51  570.75  167.40  311.15  143.48  363.57  212.77  635.69
 2023-06-16  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-19  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-20  268.07  565.80  164.58  306.37  140.15  359.04  210.40  624.75
 2023-06-21  267.24  562.69  164.73  306.83  141.82  358.49  210.10  623.66

 Instrument   U:EWD  U:NORW  ...   U:AGG   @BNDX    @TLT   U:LQD   U:HYG  \
 Field           RI      RI  ...      RI      RI      RI      RI      RI
 Currency        U$      U$  ...      U$      U$      U$      U$      U$
 Dates                       ...
 2016-12-30  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-02  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-03  465.04  156.36  ...  167.16  114.14  252.72  220.74  167.42
 2017-01-04  467.61  157.75  ...  167.21  114.20  253.70  221.50  168.33
 2017-01-05  469.22  159.39  ...  167.90  114.12  257.67  222.68  168.08
 ...            ...     ...  ...     ...     ...     ...     ...     ...
 2023-06-15  726.47  239.91  ...  177.17  119.69  250.53  247.91  199.39
 2023-06-16  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-19  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-20  701.00  233.93  ...  176.94  120.11  251.28  248.37  198.36
 2023-06-21  702.20  233.97  ...  177.23  120.13  251.89  248.09  197.86

 Instrument   U:MUB   U:HYD   U:BIL    @QQQ   U:DIA
 Field           RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$
 Dates
 2016-12-30  142.22  175.91  105.89  256.62  377.72
 2017-01-02  142.22  175.91  105.89  256.62  377.72
 2017-01-03  142.09  175.61  105.94  258.92  379.46
 2017-01-04  142.38  175.91  105.94  260.33  380.86
 2017-01-05  142.66  176.44  105.92  261.80  380.09
 ...            ...     ...     ...     ...     ...
 2023-06-15  162.03  197.58  112.75  840.21  751.99
 2023-06-16  161.92  197.62  112.77  834.92  749.72
 2023-06-19  161.92  197.62  112.79  834.92  749.72
 2023-06-20  162.12  197.58  112.83  833.72  744.27
 2023-06-21  162.27  198.04  112.84  822.36  742.02

 [1689 rows x 43 columns],
 'close': Instrument    U:VT   U:VTI   @VXUS   U:EFA   U:EWJ   U:EWU   U:EZU   U:EWL  \
 Field           RI      RI      RI      RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$      U$      U$      U$
 Dates
 2016-12-30  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-02  147.67  268.69  111.26  201.75   99.48  263.37  135.06  348.87
 2017-01-03  148.88  270.74  112.06  203.01  100.30  264.40  135.37  350.17
 2017-01-04  150.24  272.81  113.30  205.31  102.31  266.97  136.23  353.61
 2017-01-05  150.72  272.28  114.15  207.06  102.90  268.77  137.37  357.87
 ...            ...     ...     ...     ...     ...     ...     ...     ...
 2023-06-15  271.51  570.75  167.40  311.15  143.48  363.57  212.77  635.69
 2023-06-16  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-19  270.73  568.60  166.99  310.47  142.11  363.79  212.91  635.28
 2023-06-20  268.07  565.80  164.58  306.37  140.15  359.04  210.40  624.75
 2023-06-21  267.24  562.69  164.73  306.83  141.82  358.49  210.10  623.66

 Instrument   U:EWD  U:NORW  ...   U:AGG   @BNDX    @TLT   U:LQD   U:HYG  \
 Field           RI      RI  ...      RI      RI      RI      RI      RI
 Currency        U$      U$  ...      U$      U$      U$      U$      U$
 Dates                       ...
 2016-12-30  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-02  461.83  155.62  ...  166.99  114.54  251.65  220.55  166.73
 2017-01-03  465.04  156.36  ...  167.16  114.14  252.72  220.74  167.42
 2017-01-04  467.61  157.75  ...  167.21  114.20  253.70  221.50  168.33
 2017-01-05  469.22  159.39  ...  167.90  114.12  257.67  222.68  168.08
 ...            ...     ...  ...     ...     ...     ...     ...     ...
 2023-06-15  726.47  239.91  ...  177.17  119.69  250.53  247.91  199.39
 2023-06-16  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-19  720.66  238.59  ...  176.62  119.81  249.56  247.47  198.89
 2023-06-20  701.00  233.93  ...  176.94  120.11  251.28  248.37  198.36
 2023-06-21  702.20  233.97  ...  177.23  120.13  251.89  248.09  197.86

 Instrument   U:MUB   U:HYD   U:BIL    @QQQ   U:DIA
 Field           RI      RI      RI      RI      RI
 Currency        U$      U$      U$      U$      U$
 Dates
 2016-12-30  142.22  175.91  105.89  256.62  377.72
 2017-01-02  142.22  175.91  105.89  256.62  377.72
 2017-01-03  142.09  175.61  105.94  258.92  379.46
 2017-01-04  142.38  175.91  105.94  260.33  380.86
 2017-01-05  142.66  176.44  105.92  261.80  380.09
 ...            ...     ...     ...     ...     ...
 2023-06-15  162.03  197.58  112.75  840.21  751.99
 2023-06-16  161.92  197.62  112.77  834.92  749.72
 2023-06-19  161.92  197.62  112.79  834.92  749.72
 2023-06-20  162.12  197.58  112.83  833.72  744.27
 2023-06-21  162.27  198.04  112.84  822.36  742.02

 [1689 rows x 43 columns]}

In [21]:
df_master = dat['close']
df_master.columns = symbols

In [22]:
def _color_red_or_green(val):
    if val == 2:
        color = 'Green'
    elif val == 1:
        color = 'YellowGreen'
    elif val == -1:
        color = 'Tomato'
    elif val == -2:
        color = 'OrangeRed'
    else:
        color = 'white'
    return 'background-color: %s' % color

In [23]:
df_signal = pd.DataFrame(index=symbols)
for s_den in symbols:
    print(s_den)
    df = 100 * df_master.div(df_master[s_den], axis=0)
    sig = df.apply(pnf_signal)
    sig.name = s_den
    df_signal = pd.concat([df_signal, sig], axis=1)
s = df_signal.sum(axis=1)
df_out = df_signal.loc[s.sort_values(ascending=False).index, s.sort_values(ascending=True).index]
df_out.style.applymap(_color_red_or_green)

U:VT
U:VTI
@VXUS
U:EFA
U:EWJ
U:EWU
U:EZU
U:EWL
U:EWD
U:NORW
U:EWA
U:EWH
U:EPP
U:EEM
@MCHI
U:EWT
U:EWY
U:INDA
U:EWZ
U:IWM
U:VTV
U:VUG
U:XLC
U:XLY
U:XLP
U:XLE
U:XLF
U:XLV
U:XLI
U:XLB
U:XLRE
U:XLK
U:XLU
U:AGG
@BNDX
@TLT
U:LQD
U:HYG
U:MUB
U:HYD
U:BIL
@QQQ
U:DIA